### ISSUE TITLE
Consider usage of HMCharacteristicTypeVolume

### ISSUE THREAD

**Issue by hkuehl** [moecre/forked-daapd-homebridge-middleware#1]
Hi @moecre,
I really love this thingy...made me switch to Siri-control for my "home-made Sonos" all over. One question/suggestion/improvement:

Is it possible to switch to [HMCharacteristicTypeVolume](https://developer.apple.com/documentation/homekit/hmcharacteristictypevolume) instead  of using the current Light-solution?

KR
Henry

**Comment by moecre** [comment]
Hi @hkuehl,

thank you for your kind words! Really happy you could use it.

Re your request: As far as I know there are 3 services atm which can use this characteristic you mentioned: doorbell, microphone and speaker. See https://github.com/KhaosT/HAP-NodeJS/blob/d0f92c202e312717829b76c3803c86aa04fa8dc0/lib/gen/HomeKitTypes.js#L3365.

But the problem is that the current Home.app (iOS 12.2) won't display the standalone speaker service, see https://www.npmjs.com/package/homebridge-http-speaker, there is a compatibility notice which states "...Though neither the Home App nor Siri support controlling standalone Speaker services....", that's really disappointing but that's exactly the reasons why I'm doing the detour via the light solution.

Let's see what changes iOS 13 brings to the Home.app. If you have/get different information please don't hesitate to contact me. I'm really looking forward to get rid of this light bulb hack.

**Comment by hkuehl** [comment]
Thank you for the quick reply! Closing for now.
